<?php
/**
 * Created by PhpStorm.
 * User: WangChengWu
 * Date: 2018/1/8
 * Time: 18:04
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    /**
     * 与模型关联的数据表。
     *
     * @var string
     */
    protected $table = 'comment';

    /**
     * 可批量添加的字段。
     *
     * @var string
     */
    protected $fillable = ['username', 'message'];


    /* 存储时间戳 */
    protected function getDateFormat()
    {
        return time();
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }

}